export default{
    name:'product',
    title:'Product',
    type:'document',
    fields:[
        {
            name:'image',
            title:'Image',
            type:'array',
            of:[{type:'image'}],
            option:{
                hostpot:true,
            }
        },
        {
            name:'name',
            title:'Name',
            type:'string'
        },
        {
            name:'slug',
            Title:'Slug',
            type:'slug',
            option:{
                source:'name',
                maxLenght:90,
            }
        },
        {
            name:'pirce',
            title:"Price",
            type:'number',
        },
        {
            name:'details',
            title:'Details',
            type:'string',
            
        }
    ]
}